Use new-build in travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,41 +9,58 @@ cache:
 
 before_cache:
   - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
-  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
+  # remove files that are regenerated by 'cabal update'
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
+
 
 matrix:
   include:
-    - env: CABALVER=1.22 GHCVER=7.10.3
-      compiler: ": #GHC 7.10.3"
-      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}
-    - env: CABALVER=1.24 GHCVER=8.0.2
-      compiler: ": #GHC 8.0.2"
-      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}
-    - env: CABALVER=1.24 GHCVER=8.2.1
-      compiler: ": #GHC 8.2.1"
-      addons: {apt: {packages: [cabal-install-1.24,ghc-8.2.1], sources: [hvr-ghc]}}
+#    - compiler: ": #GHC 7.10.3"
+#      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-7.8.4], sources: [hvr-ghc]}}
+    - compiler: ": #GHC 8.0.2"
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-8.0.2], sources: [hvr-ghc]}}
+#    - compiler: ": #GHC 8.2.1"
+#      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-8.2.1], sources: [hvr-ghc]}}
 
 before_install:
- - unset CC
- - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
+#  - unset CC
+#  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
+#  - HC=${CC}
+#  - echo ${CC}
+#  - HCPKG=${HC/ghc/ghc-pkg}
+  - export HC=ghc
+  - unset CC
+  - PATH=/opt/ghc/bin:/opt/ghc-ppa-tools/bin:$PATH
 
 install:
- - cabal --version
- - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
- - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
-   then
-     zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
-          $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
-   fi
- - travis_retry cabal update -v
- - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
+  - cabal --version
+  - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
+  # Update
+  - travis_retry cabal update -v
+  - sed -i.bak 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
+  - "[ -f cabal.project.local  ] && exit 1 || :"
+  - "[ -f cabal.project.freeze ] && exit 1 || :"
+  # Build dependencies
+  - cabal new-build -w ${HC} --enable-tests  --project-file="cabal.project" --dep -j2 all
+  - cabal new-build -w ${HC} --disable-tests --project-file="cabal.project" --dep -j2 all
+  - rm -rf "."/.ghc.environment.* "."/dist
+  - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
 
-# Here starts the actual work to be performed for the package under test; any
-# command which exits with a non-zero exit code causes the build to fail.
-#
-# There's 3 packages in the repository so we need to build them all.
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
- - sh test-package.sh fixed-vector
- - sh test-package.sh fixed-vector-cereal
- - sh test-package.sh fixed-vector-binary
- - sh test-package.sh fixed-vector-cborg
+  # test that source-distributions can be generated
+  - for pkg in fixed-vector*; do (cd $pkg; cabal sdist); done
+  - mv ./*/dist/fixed-vector-*.tar.gz ${DISTDIR}/
+  - cd ${DISTDIR}
+  - find . -maxdepth 1 -name '*.tar.gz' -exec tar -xvf '{}' \;
+  - "echo 'packages: fixed-vector-*/*.cabal' > cabal.project"
+  # this builds all libraries and executables (without tests/benchmarks)
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks all
+  # build & run tests, build benchmarks
+  - cabal new-build -w ${HC} --enable-tests all
+  - cabal new-test  -w ${HC} --enable-tests all
